#ifndef _COMPILER_INCLUDES_DIALECT_TINYFUSIONOPS_H_
#define _COMPILER_INCLUDES_DIALECT_TINYFUSIONOPS_H_

//TODO: add inc.

#GET_CLASSES_OPS 
#include "Dialect/TinyFusionOps.h.inc"

#endif //_COMPILER_INCLUDES_DIALECT_TINYFUSIONOPS_H_