#ifndef _COMPILER_INCLUDES_DIALECT_TINYFUSIONDIALECT_H_
#define _COMPILER_INCLUDES_DIALECT_TINYFUSIONDIALECT_H_

//TODO: inc. mlir headers 
#include "Dialect/TinyFusionDialect.h.inc"

#endif //_COMPILER_INCLUDES_DIALECT_TINYFUSIONDIALECT_H_